Move to new logs
42ity/fty-outage pull request #72
Opened 2021-10-12 10:58 UTC by yarovyii

Signed-off-by: Hlib Yarovyi <HlibYarovyi@eaton.com>

2021-10-12 11:04 UTC, etnKlendathu approved these changes
What could be wrong? :)

2021-10-12 11:04 UTC, etnKlendathu commented on src/osrv.h
> +        logError("Can't load configuration from {}: %m", self->state_file);
What is %m?

2021-10-12 11:06 UTC, yarovyii commented on src/osrv.h
> +        logError("Can't load configuration from {}: %m", self->state_file);
no idea

2021-10-12 11:08 UTC, etnKlendathu commented on src/osrv.h
> +        logError("Can't load configuration from {}: %m", self->state_file);
Bad answer, maybe better to remove it?
Below same log without it.

2021-10-12 12:03 UTC, perrettecl commented on src/osrv.h
> +        logError("Can't load configuration from {}: %m", self->state_file);
It could be probably where the segfault come from...

2021-10-12 12:46 UTC, etnKlendathu commented on src/data.cc
> +        logDebug("asset: name={}, ttl={}, expires_at={}", static_cast<char*>(asset_name), e->ttl_sec,
why static_cast here? this produce a error.

2021-10-12 12:50 UTC, yarovyii commented on src/data.cc
> +        logDebug("asset: name={}, ttl={}, expires_at={}", static_cast<char*>(asset_name), e->ttl_sec,
because asset_name is void* and logDebug print out address

2021-10-12 13:54 UTC, perrettecl requested changes

2021-10-12 13:54 UTC, perrettecl commented on src/fty-outage.cc
> +        if (argn < argc - 1)
put bracket arround the if, it's safer.

2021-10-12 15:19 UTC, eric3873 commented on src/fty-outage-server.cc
> +            logDebug("Expected message of type REQUEST");
Warning ?

2021-10-12 15:21 UTC, ericclappier-eaton approved these changes

2021-10-12 15:21 UTC, eric3873 commented on src/fty-outage-server.cc
> +            logDebug("Expected zuuid");
Warning ?

2021-10-12 15:21 UTC, eric3873 commented on src/fty-outage-server.cc
> +                logDebug("Expected command");
Warning ?

2021-10-12 15:21 UTC, eric3873 commented on src/fty-outage-server.cc
> +            logDebug("'{}': invalid message type", message_type);
Warning ?

2021-10-12 15:21 UTC, eric3873 commented on src/osrv.h
> +        logDebug("There is no state path set-up, can't store the state");
Warning ?

2021-10-12 15:22 UTC, eric3873 requested changes

2021-10-12 15:22 UTC, eric3873 commented on src/osrv.h
> +        logDebug("There is no state path set-up, can't load the state");
Warning ?

2021-10-14 16:18 UTC, perrettecl approved these changes

2021-10-14 16:18 UTC, merged